#ifndef __ENT_ERRORS__
#define __ENT_ERRORS__

#include <iostream>
#include <stdexcept>

#define error_switch_case(err) \
case err: \
	type = #err; \
	break;

namespace ent {

	enum ErrorType {
		LEXER_INVALID_NUMBER_FORMAT_ERROR,
		LEXER_VALUE_OUT_OF_RANGE_ERROR,
		LEXER_INVALID_ESCAPE_CHARACTER_ERROR,
		LEXER_UNCLOSED_COMMENT_ERROR,
		LEXER_LONELY_CLOSING_COMMENT_ERROR,
		LEXER_UNKNOWN_TOKEN_ERROR,

		PARSER_EXPECTED_OTHER_ERROR,
		PARSER_INVALID_VOID_VARIABLE_ERROR,
		PARSER_INVALID_TYPE_SPECIFIER_ERROR,
		PARSER_EXPLICIT_VOID_MISSING_FN_ERROR,
		PARSER_MISSING_IF_STATEMENT_BEFORE_ELSE,
		PARSER_INVALID_EXPRESSION_IN_PARENTHESIS,
		PARSER_TRYING_TO_INCREMENT_NON_IDENTIFIER_ERROR,
		PARSER_CALLING_NON_FN_ERROR,
		PARSER_ASSIGNING_NON_IDENTIFIER_ERROR,
		PARSER_INVALID_NEGATIVE_VALUE_ERROR,
		PARSER_INVALID_ACCESS_SPECIFIER_ERROR,
		PARSER_EMPTY_TYPE_DECLARATION_ERROR,
		PARSER_EMPTY_TYPE_IMPLEMENTATION_ERROR,
		PARSER_CALLING_UNDECLARED_FN_ERROR,

		AST_CALLING_UNDECLARED_FUNCTION_ERROR,

		INTERPRETER_I8_OVERFLOW_ERROR,
		INTERPRETER_I8_UNDERFLOW_ERROR,
		INTERPRETER_I16_OVERFLOW_ERROR,
		INTERPRETER_I16_UNDERFLOW_ERROR,
		INTERPRETER_I32_OVERFLOW_ERROR,
		INTERPRETER_I32_UNDERFLOW_ERROR,
		INTERPRETER_I64_OVERFLOW_ERROR,
		INTERPRETER_I64_UNDERFLOW_ERROR,
		INTERPRETER_U8_OVERFLOW_ERROR,
		INTERPRETER_U8_UNDERFLOW_ERROR,
		INTERPRETER_U16_OVERFLOW_ERROR,
		INTERPRETER_U16_UNDERFLOW_ERROR,
		INTERPRETER_U32_OVERFLOW_ERROR,
		INTERPRETER_U32_UNDERFLOW_ERROR,
		INTERPRETER_U64_OVERFLOW_ERROR,
		INTERPRETER_U64_UNDERFLOW_ERROR,
		INTERPRETER_F32_OVERFLOW_ERROR,
		INTERPRETER_F32_UNDERFLOW_ERROR,
		INTERPRETER_F64_OVERFLOW_ERROR,
		INTERPRETER_F64_UNDERFLOW_ERROR,
		INTERPRETER_GLOBAL_OVERFLOW_ERROR,
		INTERPRETER_DIVISION_BY_ZERO_ERROR,
		INTERPRETER_INVALID_OPERATOR_ERROR,
		INTERPRETER_INVALID_OPERANDS_ERROR,
		INTERPRETER_INVALID_NUMBER_OF_ARGS_FUNCTION_ERROR,
		INTERPRETER_OUT_OF_RANGE_NUMBER,
		INTERPRETER_UNKNOWN_STATEMENT_ERROR,

		ENV_REDECLARING_EXISTING_VARIABLE_ERROR,
		ENV_SETTING_NON_EXISTING_VARIABLE_ERROR,
		ENV_GETTING_NON_EXISTING_VARIABLE_ERROR,
		ENV_REDECLARING_EXISTING_FUNCTION_ERROR,
		ENV_GETTING_NON_EXISTING_FUNCTION_ERROR,
		ENV_SETTING_NON_MUTABLE_VARIABLE_ERROR,
		ENV_INVALID_TYPE_ERROR,
	};

	class Error {
	private:
		ErrorType type;
		std::string message;

	public:
		Error(ErrorType type, std::string message) {
			this->type = type;
			this->message = message;
		}

		ErrorType get_type() {
			return this->type;
		}

		std::string get_message() {
			return this->message;
		}

		std::runtime_error error() {
			std::string type = "";
			switch(this->type) {
				error_switch_case(ErrorType::LEXER_INVALID_NUMBER_FORMAT_ERROR)
				error_switch_case(ErrorType::LEXER_VALUE_OUT_OF_RANGE_ERROR)
				error_switch_case(ErrorType::LEXER_INVALID_ESCAPE_CHARACTER_ERROR)
				error_switch_case(ErrorType::LEXER_UNCLOSED_COMMENT_ERROR)
				error_switch_case(ErrorType::LEXER_LONELY_CLOSING_COMMENT_ERROR)
				error_switch_case(ErrorType::LEXER_UNKNOWN_TOKEN_ERROR)

				error_switch_case(ErrorType::PARSER_EXPECTED_OTHER_ERROR)
				error_switch_case(ErrorType::PARSER_INVALID_VOID_VARIABLE_ERROR)
				error_switch_case(ErrorType::PARSER_INVALID_TYPE_SPECIFIER_ERROR)
				error_switch_case(ErrorType::PARSER_EXPLICIT_VOID_MISSING_FN_ERROR)
				error_switch_case(ErrorType::PARSER_MISSING_IF_STATEMENT_BEFORE_ELSE)
				error_switch_case(ErrorType::PARSER_INVALID_EXPRESSION_IN_PARENTHESIS)
				error_switch_case(ErrorType::PARSER_TRYING_TO_INCREMENT_NON_IDENTIFIER_ERROR)
				error_switch_case(ErrorType::PARSER_CALLING_NON_FN_ERROR)
				error_switch_case(ErrorType::PARSER_ASSIGNING_NON_IDENTIFIER_ERROR)
				error_switch_case(ErrorType::PARSER_INVALID_NEGATIVE_VALUE_ERROR)
				error_switch_case(ErrorType::PARSER_INVALID_ACCESS_SPECIFIER_ERROR)
				error_switch_case(ErrorType::PARSER_EMPTY_TYPE_DECLARATION_ERROR)
				error_switch_case(ErrorType::PARSER_EMPTY_TYPE_IMPLEMENTATION_ERROR)
				error_switch_case(ErrorType::PARSER_CALLING_UNDECLARED_FN_ERROR)

				error_switch_case(ErrorType::AST_CALLING_UNDECLARED_FUNCTION_ERROR)

				error_switch_case(ErrorType::INTERPRETER_I8_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I8_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I16_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I16_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I32_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I32_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I64_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_I64_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U8_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U8_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U16_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U16_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U32_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U32_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U64_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_U64_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_F32_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_F32_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_F64_OVERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_F64_UNDERFLOW_ERROR)
				error_switch_case(ErrorType::INTERPRETER_GLOBAL_OVERFLOW_ERROR)

				error_switch_case(ErrorType::INTERPRETER_DIVISION_BY_ZERO_ERROR)
				error_switch_case(ErrorType::INTERPRETER_INVALID_OPERATOR_ERROR)
				error_switch_case(ErrorType::INTERPRETER_INVALID_OPERANDS_ERROR)
				error_switch_case(ErrorType::INTERPRETER_INVALID_NUMBER_OF_ARGS_FUNCTION_ERROR)
				error_switch_case(ErrorType::INTERPRETER_OUT_OF_RANGE_NUMBER)
				error_switch_case(ErrorType::INTERPRETER_UNKNOWN_STATEMENT_ERROR)

				error_switch_case(ErrorType::ENV_REDECLARING_EXISTING_VARIABLE_ERROR)
				error_switch_case(ErrorType::ENV_SETTING_NON_EXISTING_VARIABLE_ERROR)
				error_switch_case(ErrorType::ENV_GETTING_NON_EXISTING_VARIABLE_ERROR)
				error_switch_case(ErrorType::ENV_REDECLARING_EXISTING_FUNCTION_ERROR)
				error_switch_case(ErrorType::ENV_GETTING_NON_EXISTING_FUNCTION_ERROR)
				error_switch_case(ErrorType::ENV_INVALID_TYPE_ERROR)
				error_switch_case(ErrorType::ENV_SETTING_NON_MUTABLE_VARIABLE_ERROR)
			}
			return std::runtime_error(type + ": " + this->message);
		}
	};
}

#endif // __ENT_ERRORS__